# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from strategia.protos import strategia_pb2 as strategia_dot_protos_dot_strategia__pb2


class DecisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeDecision = channel.unary_unary(
                '/strategia.DecisionService/MakeDecision',
                request_serializer=strategia_dot_protos_dot_strategia__pb2.DecisionRequest.SerializeToString,
                response_deserializer=strategia_dot_protos_dot_strategia__pb2.DecisionReply.FromString,
                )


class DecisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MakeDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeDecision,
                    request_deserializer=strategia_dot_protos_dot_strategia__pb2.DecisionRequest.FromString,
                    response_serializer=strategia_dot_protos_dot_strategia__pb2.DecisionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'strategia.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/strategia.DecisionService/MakeDecision',
            strategia_dot_protos_dot_strategia__pb2.DecisionRequest.SerializeToString,
            strategia_dot_protos_dot_strategia__pb2.DecisionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
