# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from airflower_protobufs import vlr_pb2 as vlr__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vlr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VLRStrategiaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVLRThreshold = channel.unary_unary(
                '/airflower_protobufs.VLRStrategia/GetVLRThreshold',
                request_serializer=vlr__pb2.VLRThresholdRequest.SerializeToString,
                response_deserializer=vlr__pb2.VLRThresholdResponse.FromString,
                _registered_method=True)


class VLRStrategiaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVLRThreshold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VLRStrategiaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVLRThreshold': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVLRThreshold,
                    request_deserializer=vlr__pb2.VLRThresholdRequest.FromString,
                    response_serializer=vlr__pb2.VLRThresholdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airflower_protobufs.VLRStrategia', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('airflower_protobufs.VLRStrategia', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VLRStrategia(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVLRThreshold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/airflower_protobufs.VLRStrategia/GetVLRThreshold',
            vlr__pb2.VLRThresholdRequest.SerializeToString,
            vlr__pb2.VLRThresholdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
